### ISSUE TITLE
SDE problem with sde-20170818-TRANQUILITY.zip

### ISSUE THREAD

**Issue by ion9** [SpeedProg/eve-inc-waitlist#4]
2017-09-20 22:11:17,142 - waitlist - ERROR - /usr/local/lib/python3.6/site-packages/flask/app.py - log_exception - 1560 - Exception on /settings/sde/sde/update/typeids [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1366, "Incorrect string value: '\\xE6\\xB3\\xB0\\xE5\\x9D\\xA6...' for column 'typeName' at row 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/var/www/waitlist/waitlist/blueprints/settings/staticdataimport.py", line 43, in update_type_ids
    sde.update_invtypes(dest_name)
  File "/var/www/waitlist/waitlist/utility/sde.py", line 76, in update_invtypes
    db.session.merge(inv_type)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1839, in merge
    self._autoflush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1407, in _autoflush
    util.raise_from_cause(e)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1397, in _autoflush
    self.flush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2177, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2297, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2261, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.OperationalError) (1366, "Incorrect string value: '\\xE6\\xB3\\xB0\\xE5\\x9D\\xA6...' for column 'typeName' at row 1") [SQL: 'INSERT INTO invtypes (`typeID`, `groupID`, `typeName`, description, `marketGroupID`) VALUES (%s, %s, %s, %s, %s)'] [parameters: (33857, 310, '泰坦会战遗址', '这里到处充斥着巨大舰船的残骸，无声地诉说着YC116年3月25-26日在这里爆发的那场宏大战役。 \r\n\r\n两个阵营的飞行员和他们的舰队群在这里用几千艘战舰谱写了一首壮烈的战争史诗，成就了一场史无前例的大决战。在征求了各大帝国的意见后，统合部决定留下几条战舰残骸在这里，以供后来者瞻仰唏嘘。表面上看这是对克隆飞行员的警告，提醒他们冲动是魔鬼，不过，如果你熟悉那些拥有不死之身的舰长们，你自然明白，这只会激励他们为战斗与毁灭的事业奉献终身。', None)]

**Comment by ion9** [comment]
sde-20170712-TRANQUILITY.zip same problem, i'll try removeing the item that is makeing the error.

**Comment by ion9** [comment]
after cutting out that record the next error was at this item, looks like these are the list two in the file. retrying with this one removed. moved back to the current SDE

sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.OperationalError) (1366, "Incorrect string value: '\\xE6\\xB3\\xB0\\xE5\\x9D\\xA6...' for column 'typeName' at row 1") [SQL: 'INSERT INTO invtypes (`typeID`, `groupID`, `typeName`, description, `marketGroupID`) VALUES (%s, %s, %s, %s, %s)'] [parameters: (33858, 226, '泰坦会战纪念碑', '这座纪念碑旨在缅怀于49-U6U大会战中英勇献身的84位泰坦驾驶员。它由新伊甸中的一个非官方矿工组织构思并出资建造。\r\n\r\n碧海萧\r\n魂月\r\n吉祥啊啊啊啊啊啊啊啊啊\r\n锁锁美同学提不起劲啦\r\n气双流\r\nSin Glory\r\n永远de毀灭公爵\r\n無與倫比\r\n曙 ... (534 characters truncated) ... \n宝贝灬耀\r\nTitusZ\r\nJY飞叶小鸟KOK\r\n柔情小凤仙\r\n千寻琳\r\n宝贝妞妞\r\n灿烂的轨迹\r\n爱因茨贝仑\r\n隐形人\r\n禁忌幽靈\r\n星月孤寂\r\n布鲁特林恩\r\n鸿蝇\r\n黑暗下的斗篷\r\n爱的后宫03\r\n致命诱惑哦\r\n錢包 你又瘦了', None)]

**Comment by SpeedProg** [comment]
I downloaded the sde again and it loads those types fine for me.
The error indicates that it is an encoding issue.
At this point I would need to know what character set/collation you are using on the scheme you use for the waitlist.
could you do this:
SELECT * FROM information_schema.SCHEMATA 
WHERE schema_name = "waitlist_db";

where you substitute waitlist_db for what ever you named yours.
Out put should be kind of like this:
`
CATALOG_NAME|SCHEMA_NAME|DEFAULT_CHARACTER_SET_NAME|DEFAULT_COLLATION_NAME|SQL_PATH
+
def|waitlist_db|utf8|utf8_general_ci|\N
+
`

And also:
SHOW VARIABLES LIKE  'character\_set\_%';
Where the output should be along the lines of

Variable_name|Value
character_set_client|utf8mb4
character_set_connection|utf8mb4
character_set_database|utf8
character_set_filesystem|binary
character_set_results|utf8mb4
character_set_server|utf8
character_set_system|utf8

**Comment by ion9** [comment]
good call, when i was using mysql community 5.7 i had it set to utf8, i must have missed that when i moved to mariadb. i'll try a reinstall with the new vershion and setting the DB to UTF8. 

MariaDB [(none)]> SELECT * FROM information_schema.SCHEMATA
    -> WHERE schema_name = "waitlist";
+--------------+-------------+----------------------------+------------------------+----------+
| CATALOG_NAME | SCHEMA_NAME | DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME | SQL_PATH |
+--------------+-------------+----------------------------+------------------------+----------+
| def          | waitlist    | latin1                     | latin1_swedish_ci      | NULL     |
+--------------+-------------+----------------------------+------------------------+----------+
1 row in set (0.00 sec)

MariaDB [(none)]> SHOW VARIABLES LIKE 'character_set_%';
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8                       |
| character_set_connection | utf8                       |
| character_set_database   | latin1                     |
| character_set_filesystem | binary                     |
| character_set_results    | utf8                       |
| character_set_server     | latin1                     |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
+--------------------------+----------------------------+
8 rows in set (0.02 sec)

**Comment by SpeedProg** [comment]
hey, I take it you got this fixed by changing the encoding (btw I recommend using utf8mb4 and not normal utf8)
https://mariadb.com/kb/en/library/unicode/ (basically utf8 isn't complete utf8 :(, but utf8mb4 is)

**Comment by ion9** [comment]
thank you for the heads up, i have rebuild the db.
